// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using aula2.context;

namespace aula2.Migrations
{
    [DbContext(typeof(LocalDBContext))]
    [Migration("20210413122027_projeto heroi ")]
    partial class projetoheroi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("aula2.entities.Fantasia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<bool>("capa");

                    b.Property<string>("cor");

                    b.Property<int?>("fraquesaid");

                    b.Property<int?>("poderid");

                    b.HasKey("id");

                    b.HasIndex("fraquesaid");

                    b.HasIndex("poderid");

                    b.ToTable("fantasia");
                });

            modelBuilder.Entity("aula2.entities.Fraqueza", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("fraqueza");
                });

            modelBuilder.Entity("aula2.entities.Heroi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("fantasiaid");

                    b.Property<int>("fraquesaid");

                    b.Property<string>("nome");

                    b.Property<int>("poderid");

                    b.HasKey("id");

                    b.HasIndex("fantasiaid");

                    b.HasIndex("fraquesaid");

                    b.HasIndex("poderid");

                    b.ToTable("heroi");
                });

            modelBuilder.Entity("aula2.entities.Poder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("poder");
                });

            modelBuilder.Entity("aula2.entities.Fantasia", b =>
                {
                    b.HasOne("aula2.entities.Fraqueza", "fraquesa")
                        .WithMany()
                        .HasForeignKey("fraquesaid");

                    b.HasOne("aula2.entities.Poder", "poder")
                        .WithMany()
                        .HasForeignKey("poderid");
                });

            modelBuilder.Entity("aula2.entities.Heroi", b =>
                {
                    b.HasOne("aula2.entities.Fantasia", "fantasia")
                        .WithMany()
                        .HasForeignKey("fantasiaid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("aula2.entities.Fraqueza", "fraquesa")
                        .WithMany()
                        .HasForeignKey("fraquesaid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("aula2.entities.Poder", "poder")
                        .WithMany()
                        .HasForeignKey("poderid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
